### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [Ofeabi/ProyectoFinalBioinf2017-II#2]
Ok

No olvides documentar y explicar bien en tu trabajo final porqué utilizas BUSCO, tanto la justificación biológica (el objetivo de hacerlo) como la bioinformática.

**Comment by Ofeabi** [comment]
Gracias, con respecto a la revisión de mi trabajo buscando en las bases de datos de Dryad encontre un archivo que publicaron en donde se encuentra el listado de genes ortologos presentes en los transcriptomas. Aún me cuesta trabajo entender varios puntos pero BUSCO lo que hace es verificar la calidad del ensamble en este caso del transcriptoma pero por lo que entendí tiene una base de datos llamada OrthoDB en la cual puedes realizar la busqueda de los ortologos presentes en el transcriptoma. que en este caso ya encontre el listado en Dryad. Ahora tengo una duda .. para mi proyecto de doctorado realizare una filogenia del genero agave y ya tengo las regiones de cloroplasto que utilizare en este caso las que me interesan son las regiones de nucleo para complementar mi informacion ¿del listado de genes ortologos obtenidos como se cuales son nucleares? puesto que OrthoBD da el listado de ortologos pero no especifica que sean nucleares

**Comment by Ofeabi** [comment]
otra duda... el archivo que tengo con el listado de genes ortologos es .txt pero no lo puedo abrir en un editor de textos ya que me marca que hubo un error

**Comment by Ofeabi** [comment]
@AliciaMstt

**Comment by Ofeabi** [comment]
Gracias! he tenido algunos problemas con mi proyecto, por ejemplo con la instalación de BUSCO al paracer mi computadora no tiene los requisitos necesarios para instalarlo. Me preguntaba si es posible cambiar un poco el proyecto? descargar y hacer una filogenia a partir de SNPs o alguna base de datos que me puedan proporcionar?
